# config/prometheus.yml
global:
  scrape_interval: 5s # Frecuencia con la que se recolectan métricas

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi-app:5000'] # El nombre del servicio 'fastapi-app' y su puerto