name: CI/CD Pipeline for FastAPI App

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker to trust insecure registry
        run: |
          sudo mkdir -p /etc/docker
          echo '{"insecure-registries" : ["${{ secrets.NEXUS_URL }}"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.NEXUS_URL }}/proyecto-devops/fastapi-app:v1.0.${{ github.run_number }}
