name: CI/CD Pipeline for FastAPI App

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. (NUEVO) Configura Docker para confiar en el registro HTTP de Nexus
      - name: Configure Docker to trust insecure registry
        run: |
          sudo mkdir -p /etc/docker
          echo '{"insecure-registries" : ["${{ secrets.NEXUS_URL }}"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      # 3. Inicia sesión en el repositorio Docker de Nexus
      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      # 4. Construye y etiqueta la imagen Docker
      - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ secrets.NEXUS_URL }}/proyecto-devops/fastapi-store-app:${{ github.sha }}
